from llama import Llama
from mistral import Mistral
from llama import Llama
from mpt import MPT
from tqdm import tqdm
prompt = [
    "Summarize the knowledge in the given paragraph in triples of factual knowledge in the following format: (node, relation, node). Each of the fact triple should be meaningful itself and independent to its context in the original paragraph. Here is the paragraph: See what some of our customers have to say about 1776 Steakhouse. We take great pride in ensuring the highest standards of customer satisfaction.\nLove it! We visit often. Staff is friendly and food is delightful.\nGem in a strip mall. Excellent food. Steaks melt in your mouth. Service is great. Luckily someone cancelled and we were seated quickly. Reservations highly recommended!!\nThis place has it all. Excellent food service and atmosphere. Food is some of the best i’ve had. The service was outstanding. I had a great steak and the wife had scallops. Both were done to perfection.\nWe celebrated our wedding anniversary last night. The prime rib was perfect. Loved the wedge salad. Our desserts were delicious. My husband said the creme brulee chz cake may have been the best he ever had. Great local place. Jazz was a nice touch. Relaxing after our meal.\nI love this place! The food is always excellent, regardless of what you order. Tom and his staff are always welcoming, friendly, and professional, and the service is attentive, but not intrusive. It’s by far the best steak house in town. I eat there often, and highly recommend it. You will not be disappointed.\nAmazing service and food. Never had steaks explained to me before. Definitely going back for special occasions.\nWant to taste something special?\nOur delicacy awaits to fill your tummy.\nJoin our newsletter to received updates on our promos and events. ",
    "Summarize the knowledge and events in the given paragraph in triples of factual knowledge in the following format: (node, relation, node). Each triple must content these three elements and there are separated by comma. Each of the fact triple should be meaningful itself and independent to its context in the original paragraph. If the passage talk about the author itself, denote the author as PersonX in triples. Here is the paragraph: See what some of our customers have to say about 1776 Steakhouse. We take great pride in ensuring the highest standards of customer satisfaction.\nLove it! We visit often. Staff is friendly and food is delightful.\nGem in a strip mall. Excellent food. Steaks melt in your mouth. Service is great. Luckily someone cancelled and we were seated quickly. Reservations highly recommended!!\nThis place has it all. Excellent food service and atmosphere. Food is some of the best i’ve had. The service was outstanding. I had a great steak and the wife had scallops. Both were done to perfection.\nWe celebrated our wedding anniversary last night. The prime rib was perfect. Loved the wedge salad. Our desserts were delicious. My husband said the creme brulee chz cake may have been the best he ever had. Great local place. Jazz was a nice touch. Relaxing after our meal.\nI love this place! The food is always excellent, regardless of what you order. Tom and his staff are always welcoming, friendly, and professional, and the service is attentive, but not intrusive. It’s by far the best steak house in town. I eat there often, and highly recommend it. You will not be disappointed.\nAmazing service and food. Never had steaks explained to me before. Definitely going back for special occasions.\nWant to taste something special?\nOur delicacy awaits to fill your tummy.\nJoin our newsletter to received updates on our promos and events. ",
    "Who are you?"
]

if __name__ == '__main__':
    # MODEL = Llama(load_in_8bit=False, chat=True, b13=True)
    # MODEL = Mistral(load_in_8bit=False, chat=True)
    MODEL = MPT(load_in_8bit=False, chat=True)
    prompt = prompt * 20
    for p in tqdm(prompt):
        print(MODEL.interact(p))
    